version: '3.5'
services:
  flyway:
    image: flyway/flyway
    command: -url='jdbc:mysql://teslo2.mysql.database.azure.com:3306/teslo2?&useSSL=true&user=teslo@teslo2&password=@Contamype' -baselineOnMigrate=true -connectRetries=60 migrate
    volumes:
      - ./src/migrations:/flyway/sql
    networks:
      - teslo-network
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - DATABASE_PASSWORD=${DATABASE_PASSWORD}

networks:
  teslo-network:
    driver: bridge