CREATE TABLE IF NOT EXISTS product (
  id CHAR(36) PRIMARY KEY,
  title TEXT NOT NULL,
  price FLOAT DEFAULT 0,
  description TEXT,
  slug TEXT NOT NULL,
  stock INT DEFAULT 0,
  sizes TEXT,
  gender TEXT NOT NULL,
  tags TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY (title(255)),
  UNIQUE KEY (slug(255))
);