    name: Build and deploy Node.js app to Azure Web App - sampleapp

    on:
       workflow_dispatch:

    env:
      NODE_VERSION: '18.x'
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      AZURE_WEBAPP_NAME: test-code-4   # set this to your application's name
      AZURE_WEBAPP_PACKAGE_PATH: '.'
  
    jobs:
      build:
          runs-on: ubuntu-latest
  
          steps:
          - uses: actions/checkout@v2
  
          - name: Use Node.js ${{ env.NODE_VERSION }}
            uses: actions/setup-node@v4
            with:
              node-version: ${{ env.NODE_VERSION }}
  
          - name: Install dependencies
            run: yarn install
  
          - name: Build project
            run: yarn build
  
          - name: Zip all files for upload between jobs
            run: zip --symlinks -r nest.zip ./*
                  
          - name: Upload artifact for deployment job
            uses: actions/upload-artifact@v4
            with:
              name: node-app
              path: nest.zip

      deploy:
          runs-on: ubuntu-latest
          needs: build
          environment:
           name: 'Production'
           url: $
  
          steps:
          - name: Download artifact from build job
            uses: actions/download-artifact@v4
            with:
              name: node-app
  
          - name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: ${{ env.AZURE_WEBAPP_NAME }}
              publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              package: nest.zip
  
          - name: Delete zip file
            run: rm nest.zip
