name: Staging BE release without docker

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [closed]
  
env:
  NODE_VERSION: '18.x'
  DATABASE_URL: ${{ vars.DATABASE_URL }}
  AZURE_WEBAPP_NAME: test-code-4   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'


jobs:
  build:
    if: (github.event_name == 'push' && github.ref != 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: staging

    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: build-app
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: staging

    permissions:
      contents: read
      packages: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: build-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # - name: Run Flyway Migrations
      #   env:
      #     DATABASE_URL: ${{ env.DATABASE_URL }}
      #     DATABASE_PASSWORD: ${{ secrets.DB_PASSWORD }}
      #   run: |
      #     docker compose -f docker-compose.staging.yml up flyway
